//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int IssueID { get; set; }
        public Nullable<int> Book_NO { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
